let myLastName = NhanLam;
console.log(myLastName);
let myFirstName = Quang;;
console.log(myFirstName);
let myAge = 21;
console.log(myAge);
let myAddress = "Hanoi";
console.log(myAddress);
let myHobby = "Football";
console.log(myHobby);
